### ISSUE TITLE
RFC: xml and json output

### ISSUE THREAD

**Issue by grooverdan** [akopytov/sysbench#45] opened 2016-05-05 06:02 UTC
I've done a fairly invasive set of a patches to output JSON or XML output form for sysbench tests.
It preserves the text format but adds a set of functions to define structured output. Structured results are reused in the text output.

code is here, all changes in the last commit.

https://github.com/grooverdan/sysbench/tree/1.0-report-styles (warning not fully debugged)

I was getting duplicate errors on fclose that wasn't obvious. Feedback welcome on code and I'll get to polishing it off before I do a pull request.

**Comment by akopytov** [comment] 2017-01-29 20:56
Daniel, I'm sorry, I have left this unresponded for a very long time. Mostly because of the major Lua API refactoring I've been doing.

This is now finished, and the new much extended API allows implementing custom report formats with something called 'report hooks' in a (hopefully) simple and clean way. So far the only available documentation is comments in https://github.com/akopytov/sysbench/blob/master/src/lua/internal/sysbench.lua (see the `sysbench.report_*` functions) and regression tests as examples: https://github.com/akopytov/sysbench/blob/master/tests/t/api_reports.t

I couldn't find any CSV/JSON code in the branch you referenced, so I'm not quite sure if the current implementation does what you had in mind.

Please let me know if this can be closed now.

**Comment by akopytov** [comment] 2017-01-29 20:57
Commit link just in case: https://github.com/akopytov/sysbench/commit/591c588fa71d59b19a63376b3ad46f9d1fb641c8

**Comment by akopytov** [comment] 2017-03-29 14:00
Closing for now, feel free to reopen if some of the requested functionality is missing.

**Closed by akopytov** 2017-03-29 14:00 UTC
Labels: enhancement

**Comment by grooverdan** [comment] 2017-03-29 22:07
ok. np. haven't looked at it in a while. Thanks for your consideration.

**Comment by grooverdan** [comment] 2017-03-29 22:08
Thanks for your implementation.

**Comment by flaushi** [comment] 2020-09-19 07:13
not sure if I undestood this right: is there a command line option to get json output? or do I have to write a script to get json? Thx !

**Comment by Peter2121** [comment] 2020-10-12 14:56
A small example of using sysbench.hooks.report_intermediate would be appreciated.
I cannot understand how to use it to get JSON output.

**Comment by lukx33** [comment] 2023-12-17 13:11
Can I use this (i.e. get report_cumulative in JSON) to fileio?
