### ISSUE TITLE
Different results while using parallel_prepare.lua from repo

### ISSUE THREAD

**Issue by ShahriyarR** [akopytov/sysbench#60] opened 2016-08-30 08:13 UTC
Hi dear all,
Using parallel_prepare.lua after installing using yum:
```
[root@ps-pxb-5 PTB]# sysbench --test=/usr/share/doc/sysbench/tests/db/parallel_prepare.lua --mysql-socket=/tmp/mysql_sandbox5713.sock --mysql-user=root --mysql-password=msandbox --oltp-tables-count=16 --oltp-table-size=100000 --num-threads=2 --mysql-table-engine=innodb run
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 2
Random number generator seed is 0 and will be ignored


Initializing worker threads...

thread prepare1
Creating table 'sbtest2'...
thread prepare0
Creating table 'sbtest1'...
Inserting 100000 records into 'sbtest2'
Inserting 100000 records into 'sbtest1'
Creating table 'sbtest4'...
Creating table 'sbtest3'...
Inserting 100000 records into 'sbtest4'
Inserting 100000 records into 'sbtest3'
Creating table 'sbtest6'...
Creating table 'sbtest5'...
Inserting 100000 records into 'sbtest6'
Inserting 100000 records into 'sbtest5'
Creating table 'sbtest8'...
Creating table 'sbtest7'...
Inserting 100000 records into 'sbtest8'
Inserting 100000 records into 'sbtest7'
Creating table 'sbtest10'...
Creating table 'sbtest9'...
Inserting 100000 records into 'sbtest10'
Inserting 100000 records into 'sbtest9'
Creating table 'sbtest12'...
Creating table 'sbtest11'...
Inserting 100000 records into 'sbtest12'
Inserting 100000 records into 'sbtest11'
Creating table 'sbtest14'...
Inserting 100000 records into 'sbtest14'
Creating table 'sbtest13'...
Inserting 100000 records into 'sbtest13'
Creating table 'sbtest16'...
Inserting 100000 records into 'sbtest16'
Creating table 'sbtest15'...
Inserting 100000 records into 'sbtest15'
Threads started!
```

And using parallel_prepare.lua script from cloned repo:

```
[root@ps-pxb-5 PTB]# sysbench --test=/mnt/sysbench/sysbench/tests/db/parallel_prepare.lua --mysql-socket=/tmp/mysql_sandbox5713.sock --mysql-user=root --mysql-password=msandbox --oltp-tables-count=16 --oltp-table-size=100000 --num-threads=2 --mysql-table-engine=innodb run
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 2
Random number generator seed is 0 and will be ignored


Initializing worker threads...

thread prepare0
Creating table 'sbtest1'...
Threads started!

thread prepare1
Creating table 'sbtest2'...
Inserting 100000 records into 'sbtest2'
Inserting 100000 records into 'sbtest1'
Creating secondary indexes on 'sbtest1'...
Creating secondary indexes on 'sbtest2'...
Creating table 'sbtest3'...
Creating table 'sbtest4'...
Inserting 100000 records into 'sbtest3'
Inserting 100000 records into 'sbtest4'
Creating secondary indexes on 'sbtest3'...
Creating secondary indexes on 'sbtest4'...
Creating table 'sbtest5'...
Creating table 'sbtest6'...
Inserting 100000 records into 'sbtest5'
Inserting 100000 records into 'sbtest6'
Creating secondary indexes on 'sbtest5'...
Creating secondary indexes on 'sbtest6'...
Creating table 'sbtest7'...
Creating table 'sbtest8'...
Inserting 100000 records into 'sbtest7'
Inserting 100000 records into 'sbtest8'
Creating secondary indexes on 'sbtest8'...
Creating secondary indexes on 'sbtest7'...
Creating table 'sbtest10'...
Creating table 'sbtest9'...
Inserting 100000 records into 'sbtest10'
Inserting 100000 records into 'sbtest9'
Creating secondary indexes on 'sbtest10'...
Creating secondary indexes on 'sbtest9'...
Creating table 'sbtest12'...
Creating table 'sbtest11'...
Inserting 100000 records into 'sbtest12'
Inserting 100000 records into 'sbtest11'
Creating secondary indexes on 'sbtest12'...
Creating secondary indexes on 'sbtest11'...
Creating table 'sbtest14'...
Creating table 'sbtest13'...
Inserting 100000 records into 'sbtest14'
Inserting 100000 records into 'sbtest13'
Creating secondary indexes on 'sbtest14'...
Creating secondary indexes on 'sbtest13'...
Creating table 'sbtest16'...
Creating table 'sbtest15'...
Inserting 100000 records into 'sbtest16'
Inserting 100000 records into 'sbtest15'
Creating secondary indexes on 'sbtest16'...
Creating secondary indexes on 'sbtest15'...
thread prepare1
Creating table 'sbtest2'...
ALERT: mysql_drv_query() returned error 1050 (Table 'sbtest2' already exists) for query 'CREATE TABLE sbtest2 (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
k INTEGER UNSIGNED DEFAULT '0' NOT NULL,
c CHAR(120) DEFAULT '' NOT NULL,
pad CHAR(60) DEFAULT '' NOT NULL,
PRIMARY KEY (id)
) /*! ENGINE = innodb MAX_ROWS = 1000000 */ '
FATAL: failed to execute function `event': 3
```

**Comment by akopytov** [comment] 2016-09-01 12:59
Hi Shahriyar,

As the comment in parallel_prepare.lua says, "for proper initialization use --max-requests = N, where N is --num-threads". Can you try it?

But generally, parallel_prepare.lua is dumb and needs to fixed.

**Comment by akopytov** [comment] 2016-09-01 13:02
Actually, I'm going to fix oltp.lua so it can use multiple threads (as in, honor --num-threads) on normal prepare. In that case, parallel_prepare.lua can be removed.

**Comment by akopytov** [comment] 2016-09-03 11:43
Closing for now, feel free to reopen if the problem is still there.

**Closed by akopytov** 2016-09-03 11:43 UTC
Labels: need feedback, question

**Comment by ShahriyarR** [comment] 2017-05-24 10:54
@akopytov I have noticed, it seems to be fixed with 1.0 version, right?
https://github.com/akopytov/sysbench/issues/123

**Comment by akopytov** [comment] 2017-05-24 11:00
@ShahriyarR Correct, it is fixed in 1.0.

You can now do things like:

```
sysbench oltp_read_write prepare --tables=10 --threads=8
```
Which will create 8 threads, then automatically dispatch creating and populating 10 tables to those 8 threads. No `parallel_prepare.lua` hacks, no `--max-requests` black magic is required!

**Comment by ShahriyarR** [comment] 2017-05-24 11:02
That's great :)
Thanks. So there is no need to pass full path of tests etc.

**Comment by akopytov** [comment] 2017-05-24 11:17
Yes, if you **install** sysbench, i.e. either by `make install` from the source tree, or from a binary package, then sysbench will know where to find the scripts. So for the bundled scripts, there's no need to specify the path, or even the `.lua` extension, sysbench will look in pre-defined locations.
