### ISSUE TITLE
Error during cross compilation using uclibc.

### ISSUE THREAD

**Issue by RoughTomato** [akopytov/sysbench#53] opened 2016-06-20 13:08 UTC
I was getting `undefined reference to 'rpl_malloc'` during cross compilation with usage of uclibc :
`./configure --target=mipsel-linux-uclibc --host=mipsel-linux-uclibc --without-mysql LDFLAGS="-static" `(my cross compiler is exported to $PATH).
This is due to lovely autotools while using non-glibc systems (uclibc in my case).
Quick workaround/hack can be to use:

```
#if HAVE_CONFIG_H
#include <config.h>
#endif
#undef malloc

void *malloc ();
    
void* rpl_malloc (size_t n)
{
  if (n == 0)
    n = 1;
  return malloc (n);
}
```

near the line where error occurred. Compilation goes without a problem then, and program is fully usable. In my case it was `sysbench.c:1055`.

Hope to see, a better (more elegant) solution to this problem.

Cheers!

**Comment by akopytov** [comment] 2016-06-21 07:15
Searching on the internet suggests doing `export ac_cv_func_malloc_0_nonnull=yes` before running configure may also be a workaround. Does it work for you?

**Comment by RoughTomato** [comment] 2016-06-30 11:22
Haven't found it, I'll try it having some spare time and post results thanks :) !

**Comment by akopytov** [comment] 2016-09-03 11:42
Closing for now, feel free to reopen if the problem is still there.

**Closed by akopytov** 2016-09-03 11:42 UTC
Labels: need feedback

**Comment by taismi** [comment] 2016-09-06 14:46
I tried `export ac_cv_func_malloc_0_nonnull=yes`. It worked for me.

**Comment by akopytov** [comment] 2016-09-06 14:48
Thanks for the update.
