### ISSUE TITLE
FreeBSD : PANIC: unprotected error in call to Lua API ([string "sysbench.sql.lua"]:207: Undefined symbol "db_destroy")

### ISSUE THREAD

**Issue by JBouron** [akopytov/sysbench#174] opened 2017-09-26 20:56 UTC
Hi,
For every test related to oltp I get the following panic  : 
`PANIC: unprotected error in call to Lua API ([string "sysbench.sql.lua"]:207: Undefined symbol "db_destroy")`

Context : 

-  FreeBSD 11.1
-  sysbench 1.0.9 (same with 1.0.7)
-  luaJIT-2.1.0-beta2 (same with 2.0.5)

Other tests are fine though.

Has anyone experienced the same issue ?
Thanks

**Comment by akopytov** [comment] 2017-09-27 05:28
Can you try building with `LDFLAGS=-rdynamic`?

**Comment by akopytov** [comment] 2017-10-09 13:10
Closing as there's no feedback. Feel free to reopen if the problem is still there.

**Comment by Johanhen** [comment] 2017-10-28 21:03
I had the same issue on FreeBSD 11.1 
I am no expert in this, but when i add LDFLAGS=-rdynamic to the Makefile from the ports tree Makefile file, i do not get the above error anymore.
Thank you for your time.

**Comment by akopytov** [comment] 2017-10-28 21:09
@Johanhen thanks, I'll fix default LDFLAGS for FreeBSD.

**Comment by akopytov** [comment] 2017-10-29 05:08
Should be fixed in both 1.0 and master branches now.

**Closed by akopytov** 2017-10-29 05:08 UTC
Labels: bug
