### ISSUE TITLE
Caching_sha2_password path for mysql8 

### ISSUE THREAD

**Issue by DVasyukov** [akopytov/sysbench#341] opened 2020-02-05 10:41 UTC
wrong way to **caching_sha2_password**: /usr/**/usr**/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so

**Sysbench version**: sysbench 1.0.19
**Mysql version**: Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)
**Distributor ID**: Debian
**Description**: Debian GNU/Linux 10 (buster)
**Release**: 10
**Codename**: buster

**Command**: sysbench --db-driver=mysql oltp_read_write prepare

**Error**:
FATAL: error 1045: Plugin caching_sha2_password could not be loaded: /usr//usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:83: connection creation failed 

Installation steps:
1. curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | sudo bash
2. sudo apt -y install sysbench

**Comment by akopytov** [comment] 2020-02-05 17:00
This is technically a duplicate of #244. There's not much I can fix in sysbench to fix it for Debian Buster + MySQL 8.

For workarounds, see https://lefred.be/content/sysbench-for-mysql-8-0/

**Closed by akopytov** 2020-02-05 17:00 UTC
Labels: duplicate
