### ISSUE TITLE
BINARY LONGBLOB type

### ISSUE THREAD

**Issue by yvesware** [akopytov/sysbench#237] opened 2018-06-14 15:49 UTC
I am using sysbench 1.1 

I have created a table like this:
CREATE TABLE sbtest%d(
  ....
   imm_txn INT,
   options TINYINT,
   iv BINARY,
   data LONGBLOB,
   ...
   ) 

my question is what the sysbench.sql.type, I don't see BINARY LONGBLOB. what type should I used?  Also for the create_table what string_format would match the BINARY and LONGBLOB?

**Comment by akopytov** [comment] 2018-06-14 17:50
Duplicate of #236?

**Closed by akopytov** 2018-06-14 17:50 UTC
Labels: duplicate

**Comment by yvesware** [comment] 2018-06-14 17:54
Yes sorry,
